create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean not null, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean not null, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean not null, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
create table public.massages (id  bigserial not null, tag varchar(255), text varchar(255), primary key (id));
create table public.usr (id  bigserial not null, active boolean, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
alter table user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references public.usr;
